<%@ Page Title="" Language="C#" MasterPageFile="~/admin/admin.Master" AutoEventWireup="true" CodeBehind="manage_product.aspx.cs" Inherits="jkgrocery.admin.manage_product" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <center>
    <p class="caption" style=" margin-top:15px;margin-bottom:15px; font-size:35px;">Manage Product</p>

    
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="pro_id" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="2px" CellPadding="3" GridLines="Vertical" Width="1200px" Height="60px" Font-Size="20pt" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
        <Columns>
            <asp:BoundField DataField="pro_id" HeaderText="Product Id" InsertVisible="False" ReadOnly="True" SortExpression="pro_id" />
            <asp:BoundField DataField="pro_catid" HeaderText="Product Category Id" SortExpression="pro_catid" />
            <asp:BoundField DataField="pro_name" HeaderText="Product Name" SortExpression="pro_name" />
            <asp:BoundField DataField="pro_price" HeaderText="Product Price" SortExpression="pro_price" />
          
            <asp:BoundField DataField="pro_desc" HeaderText="Product Description" SortExpression="pro_desc" />
            <asp:BoundField DataField="pro_stock" HeaderText="Stock" SortExpression="pro_stock" />
        </Columns>

        <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
            <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#0000A9" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#000065" />

</asp:GridView>

        </center>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:jaykhodiyarConnectionString5 %>" SelectCommand="SELECT [pro_id], [pro_catid], [pro_name], [pro_price], [pro_desc], [pro_stock] FROM [tbl_product]" UpdateCommand="update tbl_product set pro_catid=@pro_catid,pro_name=@pro_name,pro_price=@pro_price,pro_desc=@pro_desc,pro_stock=@pro_stock where pro_id=@pro_id" DeleteCommand="delete from tbl_product where pro_id=@pro_id">

     <DeleteParameters>
            <asp:Parameter Name="pro_id" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="pro_catid" />
            <asp:Parameter Name="pro_name" />
            <asp:Parameter Name="pro_price" />
            <asp:Parameter Name="pro_desc" />
            <asp:Parameter Name="pro_stock" />
            <asp:Parameter Name="pro_id" />
        </UpdateParameters>
</asp:SqlDataSource>

   

</asp:Content>
