<%@ Page Title="" Language="C#" MasterPageFile="~/admin/admin.Master" AutoEventWireup="true" CodeBehind="manage_category.aspx.cs" Inherits="jkgrocery.admin.manage_category" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <center>
    <p class="caption" style=" margin-top:15px;margin-bottom:15px; font-size:35px;">Manage Category</p>

    

        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="cat_id" DataSourceID="SqlDataSource4" OnSelectedIndexChanged="Page_Load" BackColor="White" BorderColor="#999999" BorderStyle="None" CellPadding="3" GridLines="Vertical" BorderWidth="2px" Width="1200px" Font-Size="20pt" Height="60px">

        <AlternatingRowStyle BackColor="white" />

            <Columns>
                <asp:BoundField DataField="cat_id" HeaderText="Category Id" InsertVisible="False" ReadOnly="True" SortExpression="cat_id" />
                <asp:BoundField DataField="cat_name" HeaderText="Category Name" SortExpression="cat_name" />
            </Columns>

            <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
            <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#0000A9" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#000065" />

        </asp:GridView>
      

    </center>

    <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:jaykhodiyarConnectionString2 %>" SelectCommand="SELECT cat_id, cat_name FROM tbl_category" UpdateCommand="update tbl_category set cat_name=@cat_name where cat_id=@cat_id;" DeleteCommand="delete from tbl_category where cat_id=@cat_id;">

        <DeleteParameters>
            <asp:Parameter Name="cat_id" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="cat_name" />
            <asp:Parameter Name="cat_id" />
            <asp:Parameter Name="cat_img" />
        </UpdateParameters>

    </asp:SqlDataSource>

</asp:Content>
