<%@ Page Title="" Language="C#" MasterPageFile="~/admin/admin.Master" AutoEventWireup="true" CodeBehind="view_user.aspx.cs" Inherits="jkgrocery.admin.view_user" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <center>
    <p class="caption" style=" margin-top:15px;margin-bottom:15px; font-size:35px;">View User</p>

    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" BackColor="#999999" BorderStyle="None" CellPadding="3" DataKeyNames="user_id" DataSourceID="SqlDataSource1" GridLines="Vertical" Height="60px" Width="1200px" Font-Size="20pt">
        <Columns>
            <asp:BoundField DataField="user_id" HeaderText="user_id" InsertVisible="False" ReadOnly="True" SortExpression="user_id" />
            <asp:BoundField DataField="user_name" HeaderText="user_name" SortExpression="user_name" />
            <asp:BoundField DataField="user_email" HeaderText="user_email" SortExpression="user_email" />
            <asp:BoundField DataField="user_phone" HeaderText="user_phone" SortExpression="user_phone" />
            <asp:BoundField DataField="user_address" HeaderText="user_address" SortExpression="user_address" />
            <asp:BoundField DataField="user_password" HeaderText="user_password" SortExpression="user_password" />
        </Columns>

        <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
            <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#0000A9" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#000065" />

    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:jaykhodiyarConnectionString7 %>" SelectCommand="SELECT * FROM [tbl_user]" DeleteCommand="delete from tbl_user where user_id=@user_id;">
        <DeleteParameters>
            <asp:Parameter Name="user_id" />
        </DeleteParameters>
    </asp:SqlDataSource>
</asp:Content>
